// <auto-generated />
using ElyraBd.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ElyraBd.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608120000_AddOrderCommerceFeatures")]
    partial class AddOrderCommerceFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model is maintained in ApplicationDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
